### ISSUE TITLE
App versions not in order

### ISSUE THREAD

**Issue by Levander0** [Sinneida/glassdown#13]
Hi, I noticed that the app versions are not in order
![Screenshot_20240209_095125](https://github.com/Sinneida/glassdown/assets/86119445/a375d073-ebd5-4a1e-8b25-8f1b276c99b8)

**Comment by Sinneida** [comment]
Yeah, apparently the site doesn't sort them by default. I'll implement it in the next version. :)

**Comment by Sinneida** [comment]
Fixed in v1.2.0
