### ISSUE TITLE
Suggestion: Ability to easily delete older apk

### ISSUE THREAD

**Issue by Levander0** [Sinneida/glassdown#14]
Would be great to have an option to delete older apk if I'm downloading a newer one.

Like this:
- Select newer Youtube apk in Glassdown
- The app asks if I want to delete an older apk I have previously downloaded.
- Starts to download newer apk.

**Comment by Sinneida** [comment]
Seems like good idea, I'll put it on Backlog.

**Comment by Sinneida** [comment]
Closed in v1.2.0, behavior can be adjusted in settings
