### ISSUE TITLE
Downloaded apk is nowhere to be found

### ISSUE THREAD

**Issue by Levander0** [Sinneida/glassdown#43]
Glassdown app says that the apk is installed but it is not. There is no apk found in my phone's storage.

**Comment by Sinneida** [comment]
Hello :)

Can you please share logs from the app? You can find them in settings, and then export logs. Logs should be exported from app to the location described under the Export option title.

And do you have latest version installed?

**Comment by Sinneida** [comment]
Okay, I think I know what's the issue. By default, APKs are saved inside Downloads folder, but native file picker disallows picking that path. If the APK cannot be saved there, then it is saved in app's default folder, which is not accessible by default. (Android/data/<glassdown package name>.

You can create new folder for GlassDown exports in phone storage or i.e. Downloads folder, then it works just fine.

I'll push a fix for that, hopefully even today.

**Comment by Levander0** [comment]
Thank you so much for the quick fix. Awesome app by the way!

**Comment by Sinneida** [comment]
Fixed in [1.5.0](https://github.com/Sinneida/glassdown/releases/tag/v1.5.0)
