### ISSUE TITLE
[Enhancement] In quick settings, add an option to include unstables only.

### ISSUE THREAD

**Issue by WelsonLiong** [Sinneida/glassdown#73]
This would be beneficial for anybody that's looking to only download beta and alpha apk from apkmirror. For example, only wanting to download WhatsApp beta from apkmirror.

This setting should be turned off by default because most user won't use it.

**Comment by Sinneida** [comment]
Sure, I'll put it in the backlog :)

**Comment by Sinneida** [comment]
Added in #47, will be available in version 2.4.0
