### ISSUE TITLE
Bad state: No element

### ISSUE THREAD

**Issue by HarshaKota** [Sinneida/glassdown#76]
I was trying to add the app "Trakt" in the app, but encountered the error in the title. 

Steps I followed are attached in the screen recording I made and also attaching the logs. 

Logs :-----
[GlassDownLogs_14_06_2024-01_13.zip](https://github.com/user-attachments/files/15831949/GlassDownLogs_14_06_2024-01_13.zip)

https://github.com/Sinneida/glassdown/assets/18014466/23f11459-c0e7-42c9-9f85-ce6130a8b34f

**Comment by Sinneida** [comment]
If you wish to add this app, you can do this by adding it from within Revanced section, added from there works normally. Nevertheless I'll check the bug today and fix it if it's feasible.

**Comment by HarshaKota** [comment]
Thank you for getting back and Yes, I can confirm adding from ReVanced section worked. 
Thank you for the alternative.

**Comment by Sinneida** [comment]
Fixed in #77, available in v2.4.1
