### ISSUE TITLE
unusable, cannot get past initial screen

### ISSUE THREAD

**Issue by mailinglists35** [Sinneida/glassdown#79]
i can tap permissions asked but there is no Next button or something to get past the opening screen

**Comment by mailinglists35** [comment]
phones tested: bv9900pro android 10, xperia 10 VI android 14

**Comment by Sinneida** [comment]
Hi, can you post a screenshot or record a screen when using the app?

**Comment by Sinneida** [comment]
Since there's no further response, I'm closing this, if you will still have issues with GlassDown in the future, create new thread

**Comment by mailinglists35** [comment]
sure, here is a video recording

https://imgur.com/a/FHkRwNv
