### ISSUE TITLE
Add App: Google Chrome - failed

### ISSUE THREAD

**Issue by arghya339** [Sinneida/glassdown#82]
Sir, how to Add app: `Google Chrome`?
https://www.apkmirror.com/apk/google-inc/chrome/

**Comment by Sinneida** [comment]
Hi :)

Apparently Google Chrome doesn't pops up on first page in APKMirror search so it is not visible in search. I'll put this fix on my todo list so it fetches more pages.

But in the meantime, you can add any app you want (i.e. Reddit) and swipe right on the app tile to edit its entries. It looks like this:
![Screenshot_20240702-154759_GlassDown.png](https://github.com/Sinneida/glassdown/assets/55593562/c6c2c2f5-3217-4ae0-a52c-48bf2e17391f)

Change the name to Chrome, and app url to just chrome like this:
![Screenshot_20240702-154822_GlassDown.png](https://github.com/Sinneida/glassdown/assets/55593562/21fb7bf5-9934-4d85-b06c-b8bc0c04e593)

This way you can "swap" any app you've added to another one, consider this as a workaround until this is fixed. :)

I've tested it and it works on my side.
