### ISSUE TITLE
Yandex Browser app icon not visible

### ISSUE THREAD

**Issue by arghya339** [Sinneida/glassdown#86]
if an [Yandex Browser with Protect](https://www.apkmirror.com/apk/direct-cursus-computer-systems-trading-llc/yandex-browser/) added to GlassDown does not yet have an app icon.
![Screenshot_20240702-200201_GlassDown.png](https://github.com/Sinneida/glassdown/assets/139842491/f6551004-65ef-4e36-b4e8-c36f1f4b8219)

**Comment by Sinneida** [comment]
That's certainly a bug, goes straight to the backlog :)

**Comment by Sinneida** [comment]
@arghya339 Hi, If you've closed the issue because of new prerelease version, don't use it until the regular release is pushed - it's certainly not ready to use & have a lot of bugs. :) I'll close the issue myself when I'll close the tickets for v2.5.0 branch

**Comment by Sinneida** [comment]
Fixed in #87
