### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [Sinneida/glassdown#89]
I see your app requests several sensitive permissions:

```
! repo/com.sinneida.glass_down2_2001.apk declares sensitive permission(s):
  android.permission.READ_EXTERNAL_STORAGE
  android.permission.MANAGE_EXTERNAL_STORAGE
  android.permission.REQUEST_INSTALL_PACKAGES
  android.permission.QUERY_ALL_PACKAGES
  android.permission.READ_MEDIA_IMAGES
  android.permission.READ_MEDIA_VIDEO
  android.permission.READ_MEDIA_AUDIO
  android.permission.READ_PHONE_STATE
```

While `QUERY_ALL_PACKAGES` and `REQUEST_INSTALL_PACKAGES` are rather clear for an app installer/updater: mind to explain the others? Especially, why the access to media storage – and why `READ_PHONE_STATE`?

Thanks in advance!

**Comment by Sinneida** [comment]
Hi :)
`READ_EXTERNAL_STORAGE` & `MANAGE_EXTERNAL_STORAGE` is used if user wants to change the default directory for files saved by GlassDown (such as exported logs, downloaded APKs and so on). By default it's separate folder inside Downloads folder, but I prefer to have it inside Internal Storage. For that this permissions are needed, AFAIR without this permission I can create files, but neither overwrite it nor delete it.
I have changed it recently to be optional (other permissions are optional as well), but TBH it'll be better to remove the option for customizing directory and have this permission removed, so it doesn't spark unnecessary controversy. I'll implement it on the next version.
Regarding the `READ_MEDIA` permissions, I haven't added it manually. Frankly speaking Android permissions are not very clear for me 😅 , but I think they're automatically added, at least according to [Android Developers page](https://developer.android.com/about/versions/13/behavior-changes-13). If I understand correctly, when I get rid of the `EXTERNAL_STORAGE` permissions, those 3 `READ_MEDIA` permissions, should be gone as well.

I also merged PR #90 with changes/fixes you've suggested, thank you for that! 😃 As soon as the the app shows up, I will merge another PR to proudly present my new Izzy badge in my README! 😃

**Comment by Sinneida** [comment]
Oh, I forgot about `READ_PHONE_STATE` permission. I'm 90% sure it's needed by the package which check for Internet connection, it the phone doesn't have any, then it disallows you tap on an app tile, instead of showing error message from HTTP client. I'm pretty sure I've checked that permission and it comes in whole package as `READ_PHONE_STATE` instead of just allowing developer to check just internet connection.

**Comment by IzzySoft** [comment]
> [storage] TBH it'll be better to remove the option for customizing directory and have this permission removed, so it doesn't spark unnecessary controversy. I'll implement it on the next version.

That would have been my suggestion. Storage permissions with SAF (Storage Access Framework) can be quite a mess up to Android 9 – but if you only need to save logs or exports and don't need access to specific areas (like Downloads, media or the SD card root) it should be not too hard to handle (hopefully).

As for the media storage permissions: those might be needed even by SAF when accessing media storage. If you don't need them, and they don't "go in peace", you can have them "go to pieces" by [Removing Unwanted Manifest Permissions With tools:node](https://developermemos.com/posts/removing-unwanted-manifest-permissions/).

As you plan to work on those I'll **not** add them to the app's "green list" for now but wait if you succeed (so they serve as a reminder, as the scan on the next release would warn again). Should they be needed, I'll "green-list" them of course.

Thanks also for applying the other changes with the PR – I'm curious now for the next release to see the versioning fixed! Not being an Android dev myself I often cannot be 100% sure, especially with all those different programming languages…

> to proudly present my new Izzy badge in my README

:heart_eyes: Looking forward to that, too!

> I'm 90% sure it's needed by the package which check for Internet connection

That'd surprise me a little, as for that there's a separate permission ([`ACCESS_NETWORK_STATE`](https://android.izzysoft.de/applists/perms#ACCESS_NETWORK_STATE)). [`READ_PHONE_STATE`](https://android.izzysoft.de/applists/perms#READ_PHONE_STATE) gives access to a bunch of sensitive details not needed for that (phone number, call state, network provider, IMEI/IMSI, etc).

**Comment by Sinneida** [comment]
I've pushed 2.6.0 on #91, got rid of `*_EXTERNAL_STORAGE` permissions, other permissions should be removed as well by the `tools:node`, versioning & changelogs should be good now and IzzyDroid badge proudly shines on README! 😊
Having my own app visible on FDroid client is huge thing for me, feels awesome as well, thanks again for accepting. 😃

I hope I've taken care of everything, but if I do left out something, it'd be great if you give me a heads up!

**Comment by IzzySoft** [comment]
Thanks a lot!

May I point you to the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) (see my comment on the PR) for some hints, especially concerning the limits? You might find some other ideas there as well (and might e.g. like to polish the `full_description.txt` with some light formatting). If you could fix that changelog before the updater starts its run (which would be around 5:30 pm UTC) that'll be great (otherwise that changelog would be truncated on import here).

```markdown
<i>GlassDown</i> is a Flutter-built client for APKMirror website. By using method known as a web scraping it allows you to add apps you frequently use and then download them, picking version and type (DPI, CPU architecture etc.) of your choice. It also includes optional integration with Revanced patches, which gives you information which version of APK you want to download is supported by the latest patches release.

<b>Features:</b>

* Adding app from APKMirror within the app
* Pick specifics of APK file you want to download (architecture, DPI etc.)
* Manage filters within settings/quick settings
* Material You theme
* Supports light/dark theme, as well as automatic switching between them synchronized with system theme
* Override app font with the one of your choice
* Revanced/Extended patches integration 
* Control removal of previously downloaded APKs
* Import/Export settings
* See logs directly in the app
* Get notified about GlassDown updates & download it directly in the app
* No tracking
* Open source (GPLv3)
* Minimal permissions
```

That's what the linked documentation describes as "Markdown Lite" and renders fine at IzzyOnDroid (Markdown2HTML), F-Droid.org ("plain text with some HTML allowed"), and even PlayStore (same plain+HTML) – though the latter is of course irrelevant until the DMA forces them to allow your app in.

**Comment by Sinneida** [comment]
I've adjusted a few things in #92 , reduced PNGs size and tried to simplify content & formatting for IzzyDroid. I took an inspiration from other apps there, I hope it'll look well 😃

**Comment by IzzySoft** [comment]
Nice! Btw, te updater takes care for optimization (like resizing screenshots to 350px on their small side, then compressing – also resizing featureGraphic to 512x250px and icon to max 20 kB in steps as far down as needed (but not below 96px), so no worries. But looks great now, thanks!

**Comment by Sinneida** [comment]
@IzzySoft I have question since I couldn't find it on IzzyDroid site - is there an option to check individual stats per app on IzzyDroid site?
